wreader:
  name: 'w-reader'
  nameHump: 'WReader'
  version: '0.0.3'
  description: 'A simple reader'
  author: 'weizhanjie'
  allowFileExtension: # 允许的文件后缀
    - 'txt'
    - 'epub'
  settings:
    singleLineChars: 30 #最大单行字数
    isShowLineNum: false #是否显示行号
    displayType: 1 #显示类型。1-侧边栏（默认），2-底部状态栏，3-左下角控制台
    dataLoadType: 1 #数据加载模式。1-网络加载，2-本地加载
    charset: 'GBK' #字符集
  componentIdKey:
    searchBook: 'SearchBookName'
    bookDirectory: 'ChapterListAction'
    prevChapter: 'PrevChapterAction'
    nextChapter: 'NextChapterAction'
    prevLine: 'PrevLineAction'
    nextLine: 'NextLineAction'
    setting: 'WReaderSetting'
  toolWindow:
    search-title: '搜索'
    font-size-sub-title: '字体-'
    font-size-add-title: '字体+'
    chapter-list-title: '目录'
    prev-chapter-title: '上一章'
    next-chapter-title: '下一章'
  language:
    java:
      name: 'java'
      commentStart: '/**'
      commentEnd: ' */'
      commentLine: ' *'
    kt:
      name: 'kotlin'
      commentStart: '/**'
      commentEnd: ' */'
      commentLine: ' *'
    js:
      name: 'javascript'
      commentStart: '/*'
      commentEnd: '*/'
      commentLine: '*'
    html:
      name: 'html'
      commentStart: '<!--'
      commentEnd: '-->'
      commentLine: ''
    xml:
      name: 'html'
      commentStart: <!--'
      commentEnd: '-->'
      commentLine: ''
    css:
      name: 'css'
      commentStart: '/*'
      commentEnd: '*/'
      commentLine: '*'
    py:
      name: 'python'
      commentStart: '"""'
      commentEnd: '"""'
      commentLine: ''
    cpp:
      name: 'cpp'
      commentStart: '/*'
      commentEnd: '*/'
      commentLine: ''
    php:
      name: 'php'
      commentStart: '/*'
      commentEnd: '*/'
      commentLine: '*'
    rs:
      name: 'rust'
      commentStart: '//'
      commentEnd: ''
      commentLine: '//'
    go:
      name: 'go'
      commentStart: '/*'
      commentEnd: '*/'
      commentLine: '*'
    yaml:
      name: 'yaml'
      commentStart: '#'
      commentEnd: ''
      commentLine: '#'
    yml:
      name: 'yaml'
      commentStart: '#'
      commentEnd: ''
      commentLine: '#'

  site_list:
    - id: 'xbiqugu.net'
      name: '笔趣阁-书香小说'
      baseUrl: 'http://www.xbiqugu.net'
      searchUrl: '/modules/article/waps.php'
      searchBookNameParam: 'searchkey'
      bookListElementName: 'grid'
      bookListElementType: 'class'
      listMainElementName: 'list'
      listMainElementType: 'id'
      chapterContentElementName: 'content'
      chapterContentElementType: 'id'
      bookNameField: 'even'
      bookUrlField: 'bookUrl'
      bookAuthorField: 'bookAuthor'
      bookDescField: 'bookDesc'
      bookImgUrlField: 'bookImgUrl'
      isHtml: true
    - id: 'xbiquzw.com'
      name: '笔趣阁-笔尖小说'
      baseUrl: 'http://www.xbiquzw.com/'
      searchUrl: '/modules/article/search.php'
      searchBookNameParam: 'searchkey'
      bookListElementName: 'grid'
      bookListElementType: 'class'
      listMainElementName: 'list'
      listMainElementType: 'id'
      chapterContentElementName: 'content'
      chapterContentElementType: 'id'
      bookNameField: 'odd'
      bookUrlField: 'bookUrl'
      bookAuthorField: 'bookAuthor'
      bookDescField: 'bookDesc'
      bookImgUrlField: 'bookImgUrl'
      isHtml: true
    - id: '3bqg.cc'
      name: '笔趣阁'
      baseUrl: 'https://www.3bqg.cc'
      searchUrl: '/user/search.html'
      searchBookNameParam: 'q'
      bookListElementName: ''
      bookListElementType: ''
      listMainElementName: 'listmain'
      listMainElementType: 'class'
      chapterContentElementName: 'chaptercontent'
      chapterContentElementType: 'id'
      bookNameField: 'articlename'
      bookUrlField: 'url_list'
      bookAuthorField: 'author'
      bookDescField: 'intro'
      bookImgUrlField: 'url_img'
      isHtml: false



