wreader:
  name: 'w-reader'
  nameHump: 'WReader'
  version: '0.0.10'
  description: 'A simple reader'
  author: 'weizhanjie'
  allowFileExtension: # 允许的文件后缀
    - 'txt'
    - 'epub'
  settings: # 设置的默认值
    singleLineChars: 30 #最大单行字数
    isShowLineNum: false #是否显示行号
    displayType: 1 #显示类型。1-侧边栏（默认），2-底部状态栏，3-左下角控制台
    dataLoadType: 1 #数据加载模式。1-网络加载，2-本地加载
    charset: 'GBK' #字符集
    autoReadTime: 5 #自动阅读时间
    voiceRole: 'Xiaoxuan' #音色
    audioTimeout: 3 #有声阅读超时
    rate: 1.0 #语速
    volume: 100 #默认音量
    audioStyle: '默认' #默认风格
  componentIdKey:
    searchBook: 'SearchBookName'
    bookDirectory: 'ChapterListAction'
    prevChapter: 'PrevChapterAction'
    nextChapter: 'NextChapterAction'
    prevLine: 'PrevLineAction'
    nextLine: 'NextLineAction'
    setting: 'WReaderSetting'
  toolWindow:
    search-title: '搜索'
    font-size-sub-title: '字体-'
    font-size-add-title: '字体+'
    chapter-list-title: '目录'
    prev-chapter-title: '上一章'
    next-chapter-title: '下一章'
  language:
    java:
      name: 'java'
      commentStart: '/**'
      commentEnd: ' */'
      commentLine: ' *'
    kt:
      name: 'kotlin'
      commentStart: '/**'
      commentEnd: ' */'
      commentLine: ' *'
    js:
      name: 'javascript'
      commentStart: '/*'
      commentEnd: '*/'
      commentLine: '*'
    html:
      name: 'html'
      commentStart: '<!--'
      commentEnd: '-->'
      commentLine: ''
    xml:
      name: 'html'
      commentStart: <!--'
      commentEnd: '-->'
      commentLine: ''
    css:
      name: 'css'
      commentStart: '/*'
      commentEnd: '*/'
      commentLine: '*'
    py:
      name: 'python'
      commentStart: '"""'
      commentEnd: '"""'
      commentLine: ''
    cpp:
      name: 'cpp'
      commentStart: '/*'
      commentEnd: '*/'
      commentLine: ''
    php:
      name: 'php'
      commentStart: '/*'
      commentEnd: '*/'
      commentLine: '*'
    rs:
      name: 'rust'
      commentStart: '//'
      commentEnd: ''
      commentLine: '//'
    go:
      name: 'go'
      commentStart: '/*'
      commentEnd: '*/'
      commentLine: '*'
    yaml:
      name: 'yaml'
      commentStart: '#'
      commentEnd: ''
      commentLine: '#'
    yml:
      name: 'yaml'
      commentStart: '#'
      commentEnd: ''
      commentLine: '#'
  # 网站列表
  # id: 网站id
  # name: 网站名称
  # baseUrl: 网站根路径
  # searchUrl: 搜索路径
  # searchBookNameParam: 搜索参数
  # searchDataBookListRule: 获取小说列表的JSONPath规则
  # searchDataBookListInfoDataRule: 获取小说列表每一列中书本信息的JSONPath规则
  # bookListElementName: 书本列表元素名
  # bookListElementType: 书本列表元素类型（class、id）
  # listMainUrl: 目录url
  # listMainElementName: 目录元素名
  # listMainElementType: 目录元素类型（class、id）
  # chapterContentUrl: 章节url
  # chapterContentHandleRule: 章节内容处理规则
  # isContentOriginalStyle: 是否使用原网页的css样式
  # replaceContentOriginalRegex: 原网页的css样式字符替换正则
  # chapterContentElementName: 章节内容元素名
  # chapterContentElementType: 章节内容元素类型（class、id）
  # bookIdField: 书籍id字段名
  # bookNameField: 书籍名字段名
  # bookUrlField: 书籍url字段名
  # bookAuthorField: 书籍作者字段名
  # bookDescField: 书籍描述字段名
  # bookImgUrlField: 书籍图片字段名
  # isHtml: 是否为html文件
  # isPathParam: 是否为路径参数
  site_list:
    - id: 'fanqienovel.com'
      name: '番茄小说'
      baseUrl: 'https://api5-normal-lf.fqnovel.com'
      searchUrl: 'https://api5-normal-lf.fqnovel.com/reading/bookapi/search/page/v/?query={key}&aid=1967&channel=0&os_version=0&device_type=0&device_platform=0&iid=466614321180296&passback={(page-1)*10}&version_code=999'
      searchBookNameParam: ''
      searchDataBookListRule: '$..book_data[*]'
      bookDataId: ''
      bookListElementName: ''
      bookListElementType: ''
      listMainUrl: 'https://fanqienovel.com/api/reader/directory/detail?bookId={bookId}'
      listMainUrlDataRule: '$..chapterListWithVolume[*].*'
      listMainItemIdField: 'itemId'
      listMainItemTitleField: 'title'
      listMainElementName: ''
      listMainElementType: ''
      chapterContentUrl: 'https://fanqienovel.com/reader/{itemId}'
      chapterContentUrlDataRule: ''
      chapterContentHandleRule: ''
      isContentOriginalStyle: true
      replaceContentOriginalRegex: '\.font-[a-zA-Z0-9]+'
      chapterContentElementName: '.muye-reader-content'
      chapterContentElementType: ''
      bookIdField: 'book_id'
      bookNameField: 'book_name'
      bookUrlField: 'bookUrl'
      bookAuthorField: 'author'
      bookDescField: 'abstract'
      bookImgUrlField: 'thumb_url'
      isHtml: false
      isPathParam: true
    - id: 'appi.kuwo.cn'
      name: '酷我小说'
      baseUrl: 'http://appi.kuwo.cn'
      searchUrl: 'http://appi.kuwo.cn/novels/api/book/search?keyword=${key}&pi=${page}&ps=30'
      searchBookNameParam: ''
      searchDataBookListRule: '$.data[*]'
      bookDataId: ''
      bookListElementName: ''
      bookListElementType: ''
      listMainUrl: 'http://appi.kuwo.cn/novels/api/book/${bookId}/chapters?paging=0'
      listMainUrlDataRule: '$.data[*]'
      listMainItemIdField: 'chapter_id'
      listMainItemTitleField: 'chapter_title'
      listMainElementName: ''
      listMainElementType: ''
      chapterContentUrl: 'http://appi.kuwo.cn/novels/api/book/${bookId}/chapters/${itemId}'
      chapterContentUrlDataRule: '$.data.content'
      chapterContentHandleRule: ''
      isContentOriginalStyle: true
      replaceContentOriginalRegex: ''
      chapterContentElementName: ''
      chapterContentElementType: ''
      bookIdField: 'book_id'
      bookNameField: 'title'
      bookUrlField: 'bookUrl'
      bookAuthorField: 'author_name'
      bookDescField: 'intro'
      bookImgUrlField: 'cover_url'
      isHtml: false
      isPathParam: true
    - id: 'www.lianjianxsw.com'
      name: '读书阁'
      baseUrl: 'http://www.lianjianxsw.com'
      searchUrl: 'url=http://www.lianjianxsw.com/search;method=POST;query_params=;body_params=keyword=${key}'
      searchBookNameParam: ''
      searchDataBookListRule: '$.data[*]'
      bookDataId: ''
      bookListElementName: ''
      bookListElementType: ''
      listMainUrl: 'http://www.lianjianxsw.com/getCataLogs?bookid=${bookId}&page=1&limit=99999'
      listMainUrlDataRule: '$.data.list[*]'
      listMainItemIdField: '_id'
      listMainItemTitleField: 'name'
      listMainElementName: ''
      listMainElementType: ''
      chapterContentUrl: 'http://www.lianjianxsw.com/getContent?bookid=${bookId}&chapterid=${itemId}'
      chapterContentUrlDataRule: '$.data.chapterInfo.content'
      chapterContentHandleRule: '<java>com.wei.wreader.utils.AESDecryption.aesBase64DecodeToTransStr(${content}, 6CE93717FBEA3E4F, AES/CBC/NoPadding, 6CE93717FBEA3E4F, {"st###":"&nbsp;&nbsp;&nbsp;&nbsp;","###$$$":"<br>&nbsp;&nbsp;&nbsp;&nbsp;"})</java>'
      isContentOriginalStyle: true
      replaceContentOriginalRegex: ''
      chapterContentElementName: ''
      chapterContentElementType: ''
      bookIdField: '_id'
      bookNameField: 'name'
      bookUrlField: 'bookUrl'
      bookAuthorField: 'author'
      bookDescField: 'intro'
      bookImgUrlField: 'cover_url'
      isHtml: false
      isPathParam: true
    - id: 'novelapi.kpkpo.com'
      name: '笔阅读器'
      baseUrl: 'https://novelapi.kpkpo.com'
      searchUrl: 'https://novelapi.kpkpo.com/api/category-search?name=${key}'
      searchBookNameParam: ''
      searchDataBookListRule: '$.result.list[*]'
      bookDataId: ''
      bookListElementName: ''
      bookListElementType: ''
      listMainUrl: 'https://novelapi-hw.tttxtt.com/h5/book-catalog-id-${bookId}'
      listMainUrlDataRule: ''
      listMainItemIdField: ''
      listMainItemTitleField: ''
      listMainElementName: '.page'
      listMainElementType: ''
      chapterContentUrl: 'https://novelapi-hw.tttxtt.com/h5/book-chapter-id-${bookId}-chapter_id-{itemId}'
      chapterContentUrlDataRule: ''
      chapterContentHandleRule: ''
      isContentOriginalStyle: false
      replaceContentOriginalRegex: ''
      chapterContentElementName: '.article'
      chapterContentElementType: ''
      bookIdField: 'id'
      bookNameField: 'name'
      bookUrlField: 'bookUrl'
      bookAuthorField: 'author'
      bookDescField: 'description'
      bookImgUrlField: 'icon'
      isHtml: false
      isPathParam: true
    - id: 'xbiqugu.net'
      name: '笔趣阁-书香小说'
      baseUrl: 'http://www.xbiqugu.net'
      searchUrl: 'http://www.xbiqugu.net/modules/article/waps.php?searchkey=${key}'
      searchBookNameParam: 'searchkey'
      searchDataBookListRule: ''
      bookDataId: ''
      bookListElementName: '.grid'
      bookListElementType: ''
      listMainUrl: ''
      listMainUrlDataRule: ''
      listMainItemIdField: ''
      listMainItemTitleField: ''
      listMainElementName: '#list'
      listMainElementType: ''
      chapterContentUrl: ''
      chapterContentUrlDataRule: ''
      chapterContentHandleRule: ''
      isContentOriginalStyle: false
      replaceContentOriginalRegex: ''
      chapterContentElementName: '#content'
      chapterContentElementType: ''
      bookIdField: 'book_id'
      bookNameField: 'even'
      bookUrlField: 'bookUrl'
      bookAuthorField: 'bookAuthor'
      bookDescField: 'bookDesc'
      bookImgUrlField: 'bookImgUrl'
      isHtml: true
      isPathParam: true
    - id: 'xbiquzw.com'
      name: '笔趣阁-笔尖小说'
      baseUrl: 'http://www.xbiquzw.com'
      searchUrl: 'http://www.xbiquzw.com/modules/article/search.php?searchkey=${key}'
      searchBookNameParam: 'searchkey'
      searchDataBookListRule: ''
      bookDataId: ''
      bookListElementName: '.grid'
      bookListElementType: ''
      listMainUrl: ''
      listMainUrlDataRule: ''
      listMainItemIdField: ''
      listMainItemTitleField: ''
      listMainElementName: '#list'
      listMainElementType: ''
      chapterContentUrl: ''
      chapterContentUrlDataRule: ''
      chapterContentHandleRule: ''
      isContentOriginalStyle: false
      replaceContentOriginalRegex: ''
      chapterContentElementName: '#content'
      chapterContentElementType: ''
      bookIdField: 'book_id'
      bookNameField: 'odd'
      bookUrlField: 'bookUrl'
      bookAuthorField: 'bookAuthor'
      bookDescField: 'bookDesc'
      bookImgUrlField: 'bookImgUrl'
      isHtml: true
      isPathParam: true
    - id: '3bqg.cc'
      name: '笔趣阁'
      baseUrl: 'https://www.3bqg.cc'
      searchUrl: 'https://www.3bqg.cc/user/search.html?q=${key}'
      searchBookNameParam: 'q'
      searchDataBookListRule: ''
      bookDataId: ''
      bookListElementName: ''
      bookListElementType: ''
      listMainUrl: ''
      listMainUrlDataRule: ''
      listMainItemIdField: ''
      listMainItemTitleField: ''
      listMainElementName: '.listmain'
      listMainElementType: ''
      chapterContentUrl: ''
      chapterContentUrlDataRule: ''
      chapterContentHandleRule: ''
      isContentOriginalStyle: false
      replaceContentOriginalRegex: ''
      chapterContentElementName: '.chaptercontent'
      chapterContentElementType: ''
      bookIdField: 'book_id'
      bookNameField: 'articlename'
      bookUrlField: 'url_list'
      bookAuthorField: 'author'
      bookDescField: 'intro'
      bookImgUrlField: 'url_img'
      isHtml: false
      isPathParam: true
#    - id: 'm.qidian.com'
#      name: '起点'
#      baseUrl: 'https://m.qidian.com'
#      searchUrl: '/soushu/${key}.html'
#      searchBookNameParam: ''
#      bookDataId: 'data-bid'
#      bookListElementName: 'y-list__content'
#      bookListElementType: 'class'
#      listMainUrl: ''
#      listMainElementName: 'listmain'
#      listMainElementType: 'class'
#      chapterContentUrl: ''
#      chapterContentElementName: 'chaptercontent'
#      chapterContentElementType: 'id'
#      bookNameField: 'articlename'
#      bookUrlField: 'url_list'
#      bookAuthorField: 'author'
#      bookDescField: 'intro'
#      bookImgUrlField: 'url_img'
#      isHtml: true
#      isPathParam: true


