wreader:
  name: 'w-reader'
  nameHump: 'WReader'
  version: '0.0.1'
  description: 'A simple reader'
  author: 'weizhanjie'
  site_list:
    - id: 'xbiqugu.net'
      name: '笔趣阁-书香小说'
      baseUrl: 'http://www.xbiqugu.net'
      searchUrl: '/modules/article/waps.php'
      searchBookNameParam: 'searchkey'
      bookListElementName: 'grid'
      bookListElementType: 'class'
      listMainElementName: 'list'
      listMainElementType: 'id'
      chapterContentElementName: 'content'
      chapterContentElementType: 'id'
      bookNameField: 'even'
      bookUrlField: 'bookUrl'
      bookAuthorField: 'bookAuthor'
      bookDescField: 'bookDesc'
      bookImgUrlField: 'bookImgUrl'
      isHtml: true
    - id: 'xbiquzw.com'
      name: '笔趣阁-笔尖小说'
      baseUrl: 'http://www.xbiquzw.com/'
      searchUrl: '/modules/article/search.php'
      searchBookNameParam: 'searchkey'
      bookListElementName: 'grid'
      bookListElementType: 'class'
      listMainElementName: 'list'
      listMainElementType: 'id'
      chapterContentElementName: 'content'
      chapterContentElementType: 'id'
      bookNameField: 'odd'
      bookUrlField: 'bookUrl'
      bookAuthorField: 'bookAuthor'
      bookDescField: 'bookDesc'
      bookImgUrlField: 'bookImgUrl'
      isHtml: true
    - id: '3bqg.cc'
      name: '笔趣阁'
      baseUrl: 'https://www.3bqg.cc'
      searchUrl: '/user/search.html'
      searchBookNameParam: 'q'
      bookListElementName: ''
      bookListElementType: ''
      listMainElementName: 'listmain'
      listMainElementType: 'class'
      chapterContentElementName: 'chaptercontent'
      chapterContentElementType: 'id'
      bookNameField: 'articlename'
      bookUrlField: 'url_list'
      bookAuthorField: 'author'
      bookDescField: 'intro'
      bookImgUrlField: 'url_img'
      isHtml: false



